### PR TITLE
Attempt to fix termguicolors

### LINKED ISSUE #54: cterm definitions for templates with dark and light backgrounds
If template has definitions for both dark and light, dark has only gui definitions:

```

hi clear
let g:colors_name = 'habamax'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 1

hi! link ErrorMsg Error
hi! link FoldColumn LineNr
hi! link LineNrAbove LineNr

..........

if &background ==# 'dark'
  let g:terminal_ansi_colors = ['#262626', '#d75f5f', '#87af87', '#afaf87', '#5f87af', '#af87af', '#5f8787', '#949494', '#626262', '#d7875f', '#afd7af', '#d7d787', '#87afd7', '#d7afd7', '#87afaf', '#bcbcbc']
  hi Normal guifg=#bcbcbc guibg=#262626 gui=NONE cterm=NONE
  hi Statusline guifg=#262626 guibg=#949494 gui=NONE cterm=NONE

  .............

  unlet s:t_Co
  finish
endif
```

### PR DESCRIPTION
**Pull request by habamax**
Should close #54

### CODE REVIEW

**Comment by habamax** [comment]
Also should address https://github.com/vim/colorschemes/issues/54

**Comment by romainl** [comment]
Yummy.

**Comment by lifepillar** [comment]
Many thanks for taking a stab at this! I have been a bit overwhelmed, but I'll take a look at it during the weekend.

**Comment by lifepillar** [comment]
Thanks again for contributing, and sorry for letting you down on this!

**Comment by habamax** [comment]
Np, thx for merging!

**Pull request merged**
