### PR TITLE
Term and cterm attributes

### PR DESCRIPTION
**Pull request by fredericmoulins**
Hi,

the main change in this PR is to import, parse and generate term and cterm attributes separately. So I guess it addresses #56. I started these changes before noticing the discussion in #56, while trying to import a colorscheme and having a `term` only attribute applying as `cterm` in the export.

These changes add a "no_italics" overwrite for the `term` attribute only for monochrome terminal.  This seems to correspond to the scheme generation but I am not sure it's right. I am not sure to understand why it was for `a:col > 2`.

Some tests are adapted but the expected results stay as is.

The other commits allow to append to the log file for repeated failed test runs, remove the ColortemplateInfoBlack highlight to avoid importing it, and remove two unused functions.

Please let me know if something needs to be changed or adapted.

### CODE REVIEW

**Comment by fredericmoulins** [comment]
If I understand correctly, an alternate take would be to keep a generic `term` attribute in colortemplate files and create a `Variant 0` scheme in addition to the `Variant gui 256` one if there is any `term` specific attribute, different from cterm's, on import.

**Comment by lifepillar** [comment]
Thanks for contributing! There's quite a bit going on in this PR, so expect me to take some time to review it.

As I mentioned in https://github.com/lifepillar/vim-colortemplate/issues/56, it is not clear to me yet whether there is a use case for having separate `term` and `cterm` at the template level. The choice to output `term` vs `cterm` depends on the variant only, AFAICS.

**Comment by lifepillar** [comment]
Sorry for the delayed feedback. First of all, thank you for taking the trouble to understand and update a somewhat messy codebase! This PR could be merged as is (but see the last paragraph below): no need to update the help files, I could do that. I am refraining from doing that right away for two reasons:

1. it introduces a change that breaks backward compatibility;
2. it is not clear to me whether having both `term` and `cterm` at the template level brings any advantage over the status quo.

I am not absolutely against breaking changes, if there is a good reason for them. But, as I have argued in https://github.com/lifepillar/vim-colortemplate/issues/56, it seems to me that there is no use case for `cterm` in templates.

Your main motivation seems to be this:

>I started these changes before noticing the discussion in https://github.com/lifepillar/vim-colortemplate/issues/56, while trying to import a colorscheme and having a `term` only attribute applying as `cterm` in the export.

Maybe, that is a bug of the import function, or something that could be somehow addressed without changing the template syntax? If so, it would be worth opening an issue and try to fix that.

@romainl claimed some ambiguity of the directive. I am not convinced, because highlight directives are always in the scope of some variants. I see `term` in templates as an abstraction for “an attribute that applies to a terminal environment”, rather than a 1-1 mapping with Vim's syntax. But my opinion is obviously biased, and I realize that `term` interpreted as I just wrote has some overloaded meaning for people who know about Vim color schemes (that is, likely the majority of people using Colortemplate).

Perhaps, we can merge this provided that a warning is produced when a `term` attribute is encountered in the context of a non b/w variant, and there is no `cterm` attribute (something like: “Highlight group Foobar defines `term` attributes, but not `cterm` attributes.”).

**Comment by fredericmoulins** [comment]
> Your main motivation seems to be this:
> 
> > I started these changes before noticing the discussion in #56, while trying to import a colorscheme and having a `term` only attribute applying as `cterm` in the export.
> 
> Maybe, that is a bug of the import function, or something that could be somehow addressed without changing the template syntax? If so, it would be worth opening an issue and try to fix that.

Yes, my motivation is about the import part: to have a template reflect the imported color scheme.

I tried to change the code this way, without changing the template syntax, after pushing this PR. It seems to be a simpler change. I have not come back to it yet to check if it works completely. 

> @romainl claimed some ambiguity of the directive.

I guess that for the attributes to be different in a color terminal and a "Variant: 0" it requires a separate "Variant: 0" in the template, whereas vim cterm and term attributes allow to express everything at once, like in a "Variant: gui 16 0".

> Perhaps, we can merge this provided that a warning is produced when a `term` attribute is encountered in the context of a non b/w variant, and there is no `cterm` attribute (something like: “Highlight group Foobar defines `term` attributes, but not `cterm` attributes.”).

What I can do is maybe:

- push the 3 unrelated commits separately;
- leave only the "import and generate term and cterm attributes" commit here;
- check and push for discussion what I tried to modify only the import function and generate a "Variant: 0";

so that it can be discussed if the breaking change is needed or not.

What do you think?

**Comment by lifepillar** [comment]
Yes, if you could split this into smaller pull requests, discussion and merging would be easier. The unproblematic commits could be merged at once, and we could focus on the crucial change.

**Comment by lifepillar** [comment]
I am closing this, as I have merged the two PRs derived from it. Thanks!

**Pull request closed without merging**
